/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FanartRouteImport } from './routes/fanart'
import { Route as EditRouteImport } from './routes/edit'
import { Route as ComicRouteImport } from './routes/comic'
import { Route as IndexRouteImport } from './routes/index'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FanartRoute = FanartRouteImport.update({
  id: '/fanart',
  path: '/fanart',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicRoute = ComicRouteImport.update({
  id: '/comic',
  path: '/comic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comic': typeof ComicRoute
  '/edit': typeof EditRoute
  '/fanart': typeof FanartRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comic': typeof ComicRoute
  '/edit': typeof EditRoute
  '/fanart': typeof FanartRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comic': typeof ComicRoute
  '/edit': typeof EditRoute
  '/fanart': typeof FanartRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/video': typeof VideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comic'
    | '/edit'
    | '/fanart'
    | '/gallery'
    | '/settings'
    | '/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comic' | '/edit' | '/fanart' | '/gallery' | '/settings' | '/video'
  id:
    | '__root__'
    | '/'
    | '/comic'
    | '/edit'
    | '/fanart'
    | '/gallery'
    | '/settings'
    | '/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComicRoute: typeof ComicRoute
  EditRoute: typeof EditRoute
  FanartRoute: typeof FanartRoute
  GalleryRoute: typeof GalleryRoute
  SettingsRoute: typeof SettingsRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fanart': {
      id: '/fanart'
      path: '/fanart'
      fullPath: '/fanart'
      preLoaderRoute: typeof FanartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comic': {
      id: '/comic'
      path: '/comic'
      fullPath: '/comic'
      preLoaderRoute: typeof ComicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComicRoute: ComicRoute,
  EditRoute: EditRoute,
  FanartRoute: FanartRoute,
  GalleryRoute: GalleryRoute,
  SettingsRoute: SettingsRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
